#!/usr/bin/env python3
"""Generate an isolation report for reviewer_supp additions.

Use after running the new scripts. It does not modify upstream outputs and writes
only ``paper_outputs/qc/reviewer_supp/_isolation_report.md``.
"""

from __future__ import annotations

import argparse
import hashlib
import subprocess
from pathlib import Path

from shared import add_common_args, default_config, write_text


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def git_status(repo: Path) -> str:
    try:
        res = subprocess.run(["git", "status", "--short"], cwd=repo, check=False, capture_output=True, text=True)
        return res.stdout.strip() or "(clean)"
    except Exception as exc:
        return f"git status unavailable: {exc}"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    add_common_args(parser)
    parser.add_argument("--repo-root", type=Path, default=Path(__file__).resolve().parents[3])
    parser.add_argument("--result-file", type=Path, default=Path(__file__).resolve().parents[1] / "result_new_meta_roi.md")
    parser.add_argument("--result-new-file", type=Path, default=Path(__file__).resolve().parents[1] / "result_new.md")
    args = parser.parse_args()
    cfg = default_config(args)
    new_files = sorted([p for p in cfg.output_root.glob("**/*") if p.is_file()]) if cfg.output_root.exists() else []
    lines = [
        "# reviewer_supp Isolation Report",
        "",
        "This report is generated by `reviewer_supp/isolation_check.py`.",
        "",
        "## Git Status",
        "",
        "```text",
        git_status(args.repo_root),
        "```",
        "",
        "## Result Document Hashes",
        "",
        f"- result_new_meta_roi.md: `{sha256(args.result_file) if args.result_file.exists() else 'missing'}`",
        f"- result_new.md: `{sha256(args.result_new_file) if args.result_new_file.exists() else 'missing'}`",
        "",
        "## reviewer_supp Output Files",
        "",
    ]
    if new_files:
        lines.extend([f"- `{p}`" for p in new_files])
    else:
        lines.append("- No reviewer_supp output files found.")
    lines.extend([
        "",
        "## Manual Verification Required",
        "",
        "- Confirm that existing scripts outside `metaphoric/final_version/reviewer_supp/` are unchanged.",
        "- Confirm that existing paper outputs outside `paper_outputs/qc/reviewer_supp/` are unchanged.",
        "- Confirm that any `result_new_meta_roi.md` diff is append-only after Section 27.",
    ])
    report = cfg.output_root / "_isolation_report.md"
    write_text("\n".join(lines) + "\n", report)


if __name__ == "__main__":
    main()
